GET http://localhost:4000/ping
//Para testar o backend usando a extensão rest client

###
//Testar os arquivos dentro de auth
POST http://localhost:4000/auth/login

###
POST http://localhost:4000/auth/registrar
content-type: application/json

{
    "nome": "Monaliza Lima 2",
    "email" : "monaliza2@gmail.com",
    "senha" : "123",
    "telefone" : "(11) 8000-9999",
    "barbeiro" : false
}

###
POST http://localhost:4000/auth/login
content-type: application/json

{
    "email" : "monaliza2@gmail.com",
    "senha" : "123"
}